### ISSUE TITLE
Tool to combine catalogs into an archive

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/CESM_catalog#4]
I think a YAML file like

```
experiment1:
  case1:
    catalog_path: [path to catalog]
    member_id: ###
  case2:
    catalog_path: [path to catalog]
    member_id: ###
experiment2:
  case3:
    catalog_path: [path to catalog]
    member_id: ###
```

would define the ensemble well enough. Each individual catalog would be read in, the experiment and member_id columns would be added, and the `ctrl_case` column would be replaced with `ctrl_experiment` and `ctrl_member_id` (assuming `ctrl_case` is also a member of the ensemble). Then all the individual catalogs would be concatenated into one giant file (we'd need to replace relative path names with absolute ones at this stage).
